"""
LangChain tool definitions for portfolio routing.

Each tool takes no parameters — they exist purely as routing signals
so the LLM can indicate which UI card to display. The actual content
is rendered entirely from static frontend data, never generated by the LLM.
"""

from langchain_core.tools import tool


@tool
def getProjects() -> str:
    """Use this when the user asks about projects, work, portfolio pieces, or things built."""
    return "Here are all my projects! Feel free to ask me more about any of them."


@tool
def getPresentation() -> str:
    """Use this when the user asks who you are, for an introduction, or background/bio info."""
    return "Here's a bit about me! Don't hesitate to ask more."


@tool
def getSkills() -> str:
    """Use this when the user asks about skills, technologies, or technical/soft skills."""
    return "Here are my skills and expertise!"


@tool
def getContact() -> str:
    """Use this when the user asks how to reach out, contact info, email, or socials."""
    return "Here's how you can reach me!"


@tool
def getExperience() -> str:
    """Use this when the user asks about work experience, internships, jobs, or professional background."""
    return "Here's my work experience!"


@tool
def getResume() -> str:
    """Use this when the user asks for a resume, CV, or wants to download a resume."""
    return "Here's my resume — feel free to download it!"


# All available tools as a list (for bind_tools)
ALL_TOOLS = [getProjects, getPresentation, getSkills, getContact, getExperience, getResume]

# Map tool function names to their caption strings
TOOL_CAPTIONS = {
    "getProjects": "Here are all my projects! Feel free to ask me more about any of them.",
    "getPresentation": "Here's a bit about me! Don't hesitate to ask more.",
    "getSkills": "Here are my skills and expertise!",
    "getContact": "Here's how you can reach me!",
    "getExperience": "Here's my work experience!",
    "getResume": "Here's my resume — feel free to download it!",
}
